live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "FiraCode Nerd Font SemBd"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[selection]
save_to_clipboard = true

[window]
blur = true
decorations = "None"
opacity = 0.7
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

